name = "day8"
description = "Advent of Code 2025 Day 8"
version = "0.1.0-dev"

authors = ["Rodrigo Garcia"]
maintainers = ["Rodrigo Garcia <rgarcia.garcia@gmail.com>"]
maintainers-logins = ["rodrigargar"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["contest"]

executables = ["day8"]
